//Copyright timeanddate.com 2005-2015, do not use without permission
var wsc="00 33 66 99 CC FF".split(" "),wsc3=["00","99","FF"],prevhtml="",prevw=500,prevh=100,sh=0,fat="",cf_prev=null,curnav=1,maxnav=6;function gv(a){return document.f[a].value}function gc(a){return document.f[a].checked}function gfc(a){return gc("f"+a)?a:""}function cfid(a){return a.replace(/_.*/,"")}function cfflash(a){return 99<cfid(a)-0}
function chsz(a){var c=gv("sz"),d=sz_cfg.a,b=document.f,e=320,g="",e=5>c;he("szdiv",!e);e?(e=sz_cfg.z[c],b.szw.value=e,b.szh.value=e*d):(e=b.szw.value,g=b.szh.value,b.szr.checked&&(1==a&&0<e&&(b.szh.value=Math.floor(e*d)),2==a&&0<g&&(b.szw.value=Math.floor(g/d))));fsu()}function scf(a,c){var d=gf("cf"+a);ac(d,"fileact",0);cf_prev&&ac(cf_prev,"fileact",0);ac(gf("cf1"),"fileact",0);var b=cfid(c),d=gf("cf"+c);ac(d,"fileact",0);b!=c&&ac(gf("cf"+b),"fileact",0);ac(d,"fileact",1);cf_prev=d}
function ccf(a){var c=document.f.cf,d=c.value;c.value=a;scf(d,a);(c=themes[a])&&c.u&&(c=c.u.replace(/^fc\d+/,"fc"+a),ncfg(c),scf(d,a));ccf_cust(a);fsu()}function ctc(){var a=document.f;a&&(a=a.html)&&(a=a.createTextRange(),a.select(),a.execCommand("Copy"))}function ffl(){var a=document.ffloat.fflcb.checked;gf("fldiv").className=a?"stck":""}
function fdpt(){var a="1"==gv("dpt"),c=gf("dptnote"),d=gf("dpt"),b=ap(d);jp(b,c,d,1,0);ep(c,b);sd(c,a);ih(c,a?'<img src="/gfx/warning.gif" width="32" height="32">Warning, only use this option if your web site is on a secure server (https). If you are unsure, select "normal"':"")}function chdpt(){fdpt();fsu()}function fsu(){gh(0,0)}function chbo(){var a=gv("bo");he("bo2",2==a);he("bo3",3==a);fsu()}function chpd(){var a=gv("pd");he("pd2",2==a);he("pd3",3==a);fsu()}
function hpal(){gf("palette").style.left="-3500px"}function updcol(a,c){var d=gv(a),b=d.replace(/[ \#]/g,""),b=b.toUpperCase();"T"==b.charAt(0)?b="transparent":("RED"==b&&(b="F00"),"BLUE"==b&&(b="00F"),"YELLOW"==b&&(b="FF0"),"WHITE"==b&&(b="FFF"),"BLACK"==b&&(b="000"),3==b.length&&(b=b.charAt(0)+b.charAt(0)+b.charAt(1)+b.charAt(1)+b.charAt(2)+b.charAt(2)),b.match("[0-9A-F]{6}")||(b=c));b!=d&&(document.f[a].value=b);if(d=gf(a+"disp"))d.style.backgroundColor="#"+b;hpal();fsu()}
function setcol(a){document.f[activecol].value=a;updcol(activecol,"")}function fst(a){var c=document.f;!a&&(a=c.tc)&&(a.value="transparent");if(a=c.pc)a.value="transparent";hpal();fsu()}function ic(){var a,c,d=arguments.length;for(c=0;c<d;c++)a=arguments[c],updcol(a,dv[a])}function ct(a){return"<td title='#"+a+"' style='background-color:#"+a+"' onclick='setcol(\""+a+"\")'>&nbsp;</td>"}
function opencol(a,c){var d,b,e,g=gf(a+"disp"),f=ap(g);g.offsetWidth&&(f.x+=g.offsetWidth+5);g=gf("palette");activecol=a;ep(g,f);g.style.zIndex=50;f="<table cellpadding=0 cellspacing=1 border=0 class='ct'><tr>";for(d=0;16>d;d++)b=String.fromCharCode(d+(9<d?55:48)),f+=ct(b+b+b+b+b+b);f=f+"</tr></table>"+("<table cellpadding=0 cellspacing=1 border=0 class='c"+c+"a'>");if(c)for(d=0;6>d;d++){f+="<tr>";for(b=0;6>b;b++)for(e=0;3>e;e++)f+=ct(wsc[d]+wsc[b]+wsc3[e]);f+="</tr>"}else for(d=0;3>d;d++){f+="<tr>";
for(b=0;3>b;b++)for(e=0;3>e;e++)f+=ct(wsc3[d]+wsc3[b]+wsc3[e]);f+="</tr>"}f+="</table>";f+="<br /><input type='button' value='"+(c?"Less colors":"More colors")+"' onclick=\"opencol('"+a+"',"+(1-c)+')">';ih(g,f)}
function fga(){var a,c,d="",b,e,g=arguments.length;for(b=0;b<g;b++){c=arguments[b];a=""+gv(c);if(c.match(/c$/)){a=a.toLowerCase();var f=a.charAt(0),h="";for(e=0;6>e;e++){var k=a.charAt(e++);k==a.charAt(e)&&(h+=k)}3==h.length&&(a=h);"t"==f&&(a="t",fat=' allowTransparency="true"')}a&&dv[c]!=a&&(a=encodeURIComponent(a).replace(/\%5C/g,"%5C%5C").replace(/\%2F/,"%5C/"),d+="/"+c+a)}return d}function getsized(a,c,d){return a.replace("widthheight",'width="'+c+'" height="'+d+'"')}
function setsize(a,c){var d=gf("exmpfr");d&&(prevw=a,prevh=c,es(d,{w:a,h:c}),document.f.html.value=getsized(lastt,a,c))}function ltalign(){for(var a=1,c,d=100,b=[];c=gf("lt"+a++);)if(c=c.rows){c=c[0].cells[0];var e=c.clientWidth;b[b.length]=c;e>d&&(d=e)}220<d&&(d=220);for(a=0;a<b.length;a++)b[a].style.width=d+"px"}function htmlfo(){var a=document.f.html;a&&(a.createTextRange?a.createTextRange().select():a.select&&a.select())}
function fnav(a){0==a?curnav=0:(1==a&&curnav--,2==a&&curnav++,0>a&&(curnav=-a),curnav=lim(curnav,1,maxnav));for(a=1;a<=maxnav;a++){var c=a==curnav||0==curnav;he("tpart"+a,c);var d=gf("navbart"+a);ac(d,"navact",c)}he("nav1",1<curnav);he("nav2",1<=curnav&&curnav<maxnav);he("navbart",0!=curnav);he("navbarten",0===curnav)};
