//Copyright timeanddate.com 2005-2015, do not use without permission
var dv={i:0,n:"0",fn:1,fc:"000",co:2};for(i=0;5>i;i++)c="abtlr".charAt(i),dv["b"+c+"c"]="000",dv["b"+c+"t"]="3",dv["b"+c+"s"]="1",dv["p"+c]="1";var heover=0,sz_cfg={a:0.421875,z:[192,256,320,448,576]};function cshe(a){heover=a;fsu()}function chtt(){fsu()}function cht(){fsu()}function cco(){var a=gv("co"),b=1<=a;he("tatr",b);he("tptr",b);b=2<=a;he("matr",b);he("mptr",b);fsu()}function chfn(a){he("fontsamp",a)}function chfn1(){document.f.fontext[gv("fn")-1].checked=!0;fsu()}
function chfn2(a){document.f.fn.value=a;fsu()}function chcl(){fsu()}function cinit(){chbo();chpd();chsz()}function p2i(){function a(a,b,e,d){a=document.f[a];d=a.value;if(!d||d<b||d>e)return sem(a,"e"),b;sem(a,"");return d-0}var b=pf(a("year",1,3999,"Year"),4),e=p2(a("month",1,12,"Month")),d=p2(a("day",1,31,"Day")),f=p2(a("hour",0,23,"Hour")),g=p2(a("min",0,59,"Minute")),k=p2(a("sec",0,59,"Second"));return b+"-"+e+"-"+d+"T"+f+":"+g+":"+k}gh_dis=0;
function gh(a,b){if(!gh_dis){a&&(sh=1,he("htmldiv",1));var e=p2i(),d;d=""+fga("i","n","cf","cm","cu","ct","cs","ca","co","cr","ss","cac","cpc","pc","tc","fn","fs","szw","szh");var f=gv("co");1<=f&&(d+=fga("tat","tac","tpt","tpc"));2<=f&&(d+=fga("mat","mac","mpt","mpc"));fat="";d+="/iso"+e;f=gv("bo");1<f&&(d=(t2=2==f?fga("bas","bat","bac"):fga("bls","blt","blc","brs","brt","brc","bts","btt","btc","bbs","bbt","bbc"))?d+t2:d+("/bo"+f));f=gv("pd");1<f&&(d=(t2=2==f?fga("pa"):fga("pl","pr","pt","pb"))?
d+t2:d+("/pd"+f));d+='" allowTransparency="true" frameborder="0" widthheight'+fat+"></iframe>\n";lastt='<iframe src="'+(1==gv("dpt")?"https://freesecure":"http://free")+".timeanddate.com/countdown"+d;document.f.html.value=getsized(lastt,prevw,prevh);h='<iframe id="exmpfr" name="exmpfr" src="onlyforusebyconfiguration.php/Zcountdown=1';heover&&(h+="/Zhe"+heover);var g=h+d;prevhtml!=h&&(prevhtml=g,setTimeout(function(){prevhtml==g&&iH("exmp",getsized(g,prevw,prevh))},1E3))}}
function ncfgs(a,b,e){var d;if(2==a)for(a=0;a<e.length;a++){if(b=e.charAt(a),b=document.f["f"+b])b.checked=!0}else{if(7==a&&(d=e.match(/(\d+)\-(\d+)\-(\d+)T(\d+):(\d+):(\d+)/))){var f=function(a,b){document.f[a].value=b};f("year",d[1]);f("month",d[2]);f("day",d[3]);f("hour",d[4]);f("min",d[5]);f("sec",d[6])}if(b=document.f[b]){if(3==a||4==a)ncfgs(1,"bo",a-1),a=1;if(5==a||6==a)ncfgs(1,"pd",a-3),a=1;if(1==a){if(f=b.options)for(d=f.length,a=0;a<d;a++){if(f[a].value==e){f[a].selected=!0;break}}else b.value=
e;if(b.onchange)b.onchange();else if(b.onblur)b.onblur()}}}}function ncfgsd(a,b,e){ncfgs(a,b,decodeURIComponent(e))}
function ncfg(a){var b,e,d=a.match(/\/[^\/]+/g);document.f.reset();var f={i:1,n:1,tl:1,fn:1,fs:1,fc:1,tc:1,pc:1,ah:1,av:1,bo:1,bas:3,bat:3,bac:3,bls:4,blt:4,blc:4,brs:4,brt:4,brc:4,bts:4,btt:4,btc:4,bbs:4,bbt:4,bbc:4,tac:1,mac:1,cac:1,tpc:1,mpc:1,cpc:1,tat:1,mat:1,tpt:1,mpt:1,pd:1,pa:5,pl:6,pr:6,pt:6,pb:6,dpt:1,iso:7};if(d)for(a=0;a<d.length;a++)b=d[a],e=b.substring(1,2),f[e]?(ncfgsd(f[e],e,b.substring(2)),"i"==e&&delete f[e]):(e=b.substring(1,3),f[e]?ncfgsd(f[e],e,b.substring(3)):(e=b.substring(1,
4),f[e]&&ncfgsd(f[e],e,b.substring(4))));cinit();fsu();return!1}function impbutclk(){he("impbut",0);he("impmsg",0);document.f2.srccode.value="";he("imparea",1)}
function impbut(a){var b="";if(1==a){var e=document.f2.srccode.value;a="";20>e.length?a="Please paste the HTML in the field below":(e=e.match(/http(.?)\:\/\/free\w*\.timeanddate\.com\/countdown(\/[^\"\']+)/))?(b=e[2],"s"==e[1]&&(b+="/dpt1")):a="Was not able to find countdown from timeanddate.com in supplied HTML";if(a&&(e=gf("impmsg"))){ih(e,"Error: "+a);sd(e,1);return}}he("impbut",1);he("imparea",0);b&&ncfg(b)}
function init(){cinit();gh_dis=1;try{ltalign(),ic("tac","mac","cac","tpc","mpc","cpc"),cco(),ffl(),fdpt()}catch(a){}gh_dis=0;gh(0,1)}function ccf_cust(a){var b=themes[a];b&&(a=function(a,d){var f=b[d];he(a+"r",!!f);f?(document.f[a].value=f,updcol(a)):"pc"==a&&(document.f.pc.value="FFFFFF")},a("pc","b"),a("tc","s"))}ael(window,"load",init);
