//Copyright timeanddate.com 2005-2015, do not use without permission
Mf=Math.floor;Mr=Math.random;function pf(a,b){a=""+a;var c=b-a.length;0<c&&(a="0000000000".slice(10-c)+a);return a}function p2(a){return 10>a?"0"+a:a}function lim(a,b,c){return Math.max(Math.min(a,c),b)}function dt(){return(new Date).getTime()}function it(a,b){if(a){var c=a.length,d;for(d=0;d<c;d++)b(a[d],d)}}function ia(a,b){if(a)for(var c in a)a.hasOwnProperty(c)&&b(c,a[c])}
function sprintf(a){var b=Array.prototype.slice.call(arguments,1);return a.replace(/\%(\d*)(\.?)(\d*)([ds])/g,function(a,d,e,f,g){a=b.shift();if("s"==g)return a;if("d"==g)return g=a-0,0<=f?g.toFixed(f):g})}ph={};function gx(){function a(a){try{if(c.ActiveXObject)return new ActiveXObject(a)}catch(b){}}var b=null,c=window;try{c.XMLHttpRequest&&(b=new XMLHttpRequest)}catch(d){}b||(b=a("Msxml2.XMLHTTP"));b||(b=a("Microsoft.XMLHTTP"));return b}
function gp(a,b,c){if(a)try{return a.open("GET",("https:"==document.location.protocol?"https://":"http://")+document.domain+b,!0),a.onreadystatechange=c,a.send(""),1}catch(d){alert(d)}return 0}function rs4(a){if(a&&4==a.readyState){if(200!==a.status){errm="rs4:status="+a.status;return}return a.responseText+""}return!1}
function ghj(a){var b={j:""},c=a.indexOf("<script");if(0<=c){var d=a.indexOf(">",c);if(0<=d){var e=a.indexOf("\x3c/script>",d);0<e&&(b.j+=a.slice(d+1,e),a=a.slice(0,c)+a.slice(e+9))}}b.h=a;return b}function jcb(a,b){var c=gx();return c?(gp(c,a,function(){var a=rs4(c);a&&b(a)}),!0):!1}function rf(a,b,c,d){iH(a,b);a=Mf(1E3*(c+Mr()*d));setTimeout(function(){location.reload()},a)}function phg(a,b,c){var d=ph[a];d?c(d):jcb(b,function(b){ph[a]=b;c(b)})}
function gf(a){if("string"===typeof a){var b=document;return b.getElementById?b.getElementById(a):b.all?b.all[a]:null}return a}function cE(a,b,c){var d=document.createElement(a);ia(b,function(a,b){"class"===a?d.className=b:sA(d,a,b)});aCh(c,d);return d}function aCh(a,b){a&&b&&a.appendChild(b)}dce=cE;function hC(a,b){var c=a.className;return c&&0<=(" "+c+" ").indexOf(" "+b+" ")}function gA(a,b){return a.getAttribute(b)}function sA(a,b,c){return a.setAttribute(b,c)}
function ddE(){return document.documentElement}function arrclone(a){var b=[],c=a.length,d;for(d=0;d<c;d++)b[d]=a[d];return b}function gebc(a,b){b||(b=document);var c;if(b.getElementsByClassName)return c=b.getElementsByClassName(a),arrclone(c);var d=b.firstChild,e=[];if(d){do 1==d.nodeType&&(d.className&&hC(d,a)&&e.push(d),(c=gebc(a,d)).length&&(e=e.concat(c)));while(d=d.nextSibling)}return arrclone(e)}function gebn(a,b){b||(b=document);var c=b.getElementsByName(a);return arrclone(c)}
function gebtn(a,b){if("string"===typeof b&&(b=gf(b),!b))return[];b||(b=document);var c=b.getElementsByTagName(a);return arrclone(c)}function gebtn0(a,b){var c=gebtn(a,b);c&&(c=c[0]);return c}function ih(a,b){a&&(a.innerHTML=b)}function iH(a,b){ih(gf(a),b)}function sd(a,b){a&&(a.style.display=b?2==b?"block":"":"none")}function he(a,b){sd(gf(a),b)}function ee(a,b,c){if(a=a[b])a.disabled=!c}
function ac(a,b,c){if(a){a=gf(a);var d=a.className+" ",e=" "+d,f=e.indexOf(" "+b+" ");if(c){if(0<=f)return;d+=b}else{if(0>f)return;d=d.substring(0,f)+e.substring(f+b.length+1)}a.className=d}}function po(a){for(var b={x:0,y:a.offsetHeight};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b}
function ap(a,b){var c=0,d=0,e=0;if(a.getBoundingClientRect&&navigator.appVersion.match(/MSIE [3-7]/))var d=ddE(),f=a.getBoundingClientRect(),c=f.left+d.scrollLeft,d=f.top+d.scrollTop;else for(;a;)"fixed"==gcst(a,"position")&&(e=1),c+=a.offsetLeft,d+=a.offsetTop,a=a.offsetParent;return{x:c,y:d,f:e}}function isdef(a){return void 0!==a}function ep(a,b){var c=a.style;isdef(b.x)&&(c.left=b.x+"px");isdef(b.y)&&(c.top=b.y+"px");isdef(b.f)&&(c.position=b.f?"fixed":"absolute")}
function gcst(a,b){var c=window.getComputedStyle;if(c)return c(a,null).getPropertyValue(b);if(c=a.currentStyle)return c[b]}
function gcs(a,b){var c=window.getComputedStyle,d=function(a,b){var c=/^[0-9\.]+(px)?$/i;if(0<parseFloat(b)){if(c.test(b))return parseInt(b);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b||0;b=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d}else b=0;return b};if(c){if(c=c(a,null))return d(a,c.getPropertyValue(b))}else if(c=a.currentStyle)return c=c[b],"height"==b&&"auto"==c&&(c=a.offsetHeight-gcs(a,"marginTop")-gcs(a,"marginBottom")),d(a,c);
return null}function es(a,b){var c=a.style;0<b.w&&(c.width=b.w+"px");0<b.h&&(c.height=b.h+"px")}function esp(a,b){var c=a.style;0<b.w&&(c.width=b.w+"%");0<b.h&&(c.height=b.h+"%")}function esa(a,b){es(a,b);ep(a,b)}function sw(a){var b=[],c=0;it(a,function(a,e){b[e]=a;var f=a.offsetWidth;f>c&&(c=f)});it(b,function(a){es(a,{w:c})})}
function jp(a,b,c,d,e,f){var g=b.offsetWidth,k=c.offsetWidth;c=c.offsetHeight;-1E3>d&&(a.x+=d+1E3,d=-1);-1==d&&(a.x-=g-k);1==d&&(a.x+=k);2==d&&(a.x+=(k-g)/2);-1==e&&(a.y-=c);1==e&&(a.y+=c);2==e&&(a.y+=(c-b.offsetHeight)/2);0>a.x&&(a.x=0);f&&a.x+g>window.innerWidth&&(a.x-=a.x+g-window.innerWidth)}
function siv(a,b,c,d){var e=ddE(),f=0,g=0,k=0,q=void 0!==c?c:1E3,l=void 0!==d?l:function(a){return 1==a?1:1-Math.pow(2,-10*a)};c=function(){function a(c){c=dt()-b;c=0>c?0:c;c>=q?p(1):k===h()?(p(c/q),raf(a)):p(1)}var b=dt();raf(a)};var h=function(){return void 0!==window.pageYOffset?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop},p=function(a){a=l(a);k=Mf(g+(f-g)*a);window.scrollTo(0,k)};a=gf(a);d=ap(a);var n=h();if(d.y+a.clientHeight>n+e.clientHeight||
b)f=b?d.y-30:Math.min(d.y-e.clientHeight+a.clientHeight,d.y-30),g=k=n,c();return!1}function gsv(){var a=ddE(),a={w:window.innerWidth||document.body.clientWidth,h:document.height||document.body.scrollHeight,W:a?a.clientWidth:980,H:a?a.clientHeight:600};a.H>a.h&&(a.h=a.H);return a}
UA=function(){function a(a){var d;for(d=0;d<a.length;d++)if(a[d]in b)return a[d];return!1}var b=cE("a").style;return{trans:a(["transform","webkitTransform","MozTransform","OTransform","msTransform"]),d3:a(["perspective","webkitPerspective","MozPerspective","OPerspective","msPerspective"]),mat:function(a,b){b=b||1;var e=2*Math.PI/360*a,f=Math.cos(e),e=Math.sin(e);return"progid:DXImageTransform.Microsoft.Matrix(M11="+f*b+",M12="+-e*b+",M21="+e*b+",M22="+f*b+",SizingMethod='auto expand')"}}}();
function wl(a){var b=window.location;a&&(b.href=a);return b}function gso(a){return a.options[a.selectedIndex]}function gfv(a){var b=a.type;if(b)switch(b){case "select-one":return gso(a).value;case "radio":if(a.checked)return a.value;break;case "checkbox":return a.checked?a.value:"";case "button":case "submit":break;default:return a.value}return null}function ga(a){var b=[],c=a.elements,d=c.length,e,f;for(e=0;e<d;e++)a=c[e],f=gfv(a),null!==f&&(b[a.name]=f);return b}
function au(a){var b=[],c=0,d;for(d in a)""!==d&&(b[c++]=d+="="+escape(a[d]));return b.join("&")}function ru(a,b){var c,d=b.split("&");a=a.replace(/\?/,"?&");for(c=0;c<d.length;c++){var e=d[c],f=e.indexOf("=");0<f&&(f=e.substr(0,f+1),f=a.indexOf("&"+f),a=0<f?a.substring(0,f+1)+e+a.substring(f+1):a+("&"+e))}return a.replace(/\?\&/,"?")}function hu(a){return a.replace(/\&/,"&amp;")}function aau(a){it(a.elements,function(a){sA(a,"autocomplete","off")})}
function dau(a){it(a.elements,function(a){a.removeAttribute("autocomplete")})}sem_a={};function sem(a,b){var c=a.name;if(sem_a[c]!=b){sem_a[c]=b;var d=gf("e"+c),c=gf(c);d&&(ih(d,b),ac(d,"errmark",b));c&&ac(c,"errf",b)}}function jsav(a,b){a+="&"+au(ga(b));jcb(a,function(a){var b="Some error occured - was not able to save";a.match(/JS:/)&&(b="Please wait - reloading page now",location.reload());iH("jcdiv",b)})}menact=null;men={};function PU(a){this.n=a;this.s=0;PU.p[PU.p.length]=this}PU.p=[];
PU.C=function(a){it(PU.p,function(b){b!=a&&b.k()})};PU.prototype.i=function(a){var b=this.e,c=1;it(a,function(a){a==b&&(c=0)});c&&200<dt()+this.s&&this.k()};var trkclk=0.2>Mr();
ael(window,"click",function(a){var b=ev(a);a=b.s;a=b.e;a=a.target||a.currentTarget||a.relatedTarget||a.fromElement||a.srcElement;for(var c=[],b=a;b;){var d=b.parentNode;c[c.length]=b;b=d}it(PU.p,function(a){a.s&&a.i(c)});if(a&&trkclk&&((b=a.href)||(b="submit"==a.type?"submit":c[1].href),b)){var e="";c.pop();c.pop();it(c,function(a){var b=a.tagName;b&&(e=b+":"+a.id+";"+a.className+">"+e)});e=window.location.pathname+">>"+e+">>"+b+">>"+a.innerHTML;document.cookie="LINKUSED="+escape(e)+";domain=.timeanddate.com;path=/"}});
PU.prototype.h=function(a){var b=gf(this.n);this.e=b;ih(b,a);this.o();return b};PU.prototype.d=function(a){var b=gf(this.n);this.e=b;aCh(b,a);this.o();return b};PU.prototype.E=function(a){this.e=a;if(a=a.id)this.n=a};PU.prototype.y=function(){this.s=-dt()};PU.prototype.o=function(){this.y();PU.C(this);sd(this.e,2)};PU.prototype.k=function(){sd(this.e,0);this.s=0;this.c&&this.c()};PU.prototype.x=function(a){a&&a!=this.s||0<=this.s&&this.k()};
PU.prototype.z=function(a){var b=this;a=a||330;var c=dt()+a;b.s=c;window.setTimeout(function(){b.x(c)},a+100)};PU.prototype.A=function(a,b,c,d){a=ghj(a);var e=this.h(a.h),f=ap(b);jp(f,e,b,c||0,1,d);ep(e,f);eval(a.j)};pM=new PU("po1");function mena(a,b){b.n=a;var c=a.indexOf("txt");0<c&&(b.N=a.slice(0,c));men[a]=b}function menh(a){var b=menact;if(b){var c=b.e.getElementsByTagName("li");if(c){var d=function(a,b){"number"===typeof a&&0<=a&&a<c.length&&ac(c[a],"h",b)};d(b.h,0);d(a,1);b.h=a}}}
function mech(a,b){if(b)if(a.f)a.f(a,b);else if(a.i.value=b.n,a.g&&b.U)wl(b.U);else{if(a.I){a.I.value=b.U;var c=fh[a.n];c.H=b.U;c.T=b.n}va(a.i.id,a.i)}pM.k()}function menc(a){var b=menact;b&&(a=b.a[a])&&mech(b,a)}function menfr(){var a=menact;if(a&&(a=a.a[0])&&a.U)return 1}function mmenc(){menfr()&&menc(0)}
function mens(a,b){var c=men[a];if(c){var d=ap(b),e=c.u?c.u.replace(/\&amp\;/g,"&"):"/",f=0,g=c.c||"mn",k=c.C||g,g="<div class="+g+" onmouseout='pM.z()'>",q=c.a.length,l=c.r,h=0,p=l&&l<q,n=1;p?(n=Mf((q+l-1)/l),g+="<table><tr>"):l=q;for(;n--;){for(var h=h+l,r="<ul class="+k+">";f<q&&f<h;f++){var s=c,m=f,v=n,u=f+1>=h,t=s.a[m],w="";if(1===t.s)w+="<li class=mnd>&nbsp;";else{var x="";t.p&&(x=hu(ru(e,t.p)));t.u&&(x=t.u);v=(v=(v?"lr":"")+(u?" ls":""))?"class='"+v+"' ":"";u="h";t.s&&(u+=" asb");w+="<li onmouseover='pM.y()'"+
(t.h?" class='"+u+"' ":"")+">";u=t.n+(t.d||"");t.c&&(u="<span class="+t.c+">"+u+"</span>");if(2!==t.s)if(x)u="<a "+v+"href='"+x+"'>"+u;else if(s.i||t.v)u="<a "+v+"href='javascript:menc("+m+")'>"+u;w+=u;t.x&&(w+="<span class=mnx>"+t.x+"</span>");w+="</a>"}w+="</li>";r+=w}r+="</ul>";g=p?g+("<td valign=top>"+r+"</td>"):g+r}p&&(g+="</tr></table>");menact=c;e=pM.h(g);c.e=e;c.i&&(e.style.width="",f=c.i.offsetWidth,e.offsetWidth<f&&es(e,{w:f}),c.N&&(c.I=c.i.form[c.N]));jp(d,e,b,"undefined"!=typeof c.j?c.j:
-1,1);"asu"==c.C&&(d.x-=2,d.y+=5);c=b.offsetWidth;f=e.offsetWidth;f<c||350<c?es(e.firstChild,{w:c}):f>c&&350<f&&es(e.firstChild,{w:300});ep(e,d)}}function mensk(a,b){mens(a,b)}getAC=function(){var a={};return function(b){var c=a[b];c||(c=new AC(b),a[b]=c);return c}}();function AC(a){this.t=a;this.c={};this.l=null;this.p="";this.f=null;this.h={}}AC.prototype.C=function(a){var b=this;a=a.toLowerCase();return a=a.replace(/[^\020-\177]/g,function(a){var d=b.h[a];"string"===typeof d&&(a=d);return a})};
AC.prototype.B=function(a,b){var c=function(a,b){var c=a.indexOf(b);if(0>c)return 0;var d=b.length;if(0===c)return d;if(65>a.charCodeAt(c-1))return 0.9*d;var e=b.length;if(2>e)return 0;d*=(e+0.1)/(e+5);a=a.substr(0,c);return(c=a.match(/([\040-\077]+)/))?0.5*d/(1+c.length):0.1},d=function(a,b,c){c=(c=b.s)?c+(" - "+b.c):c+b.c;a.a[a.a.length]={c:"ash",n:b.n,x:c,U:b.i,h:0,d:b.f?"<img height=16 width=16 class=fr alt=Flag src='"+b.f+"'>":""}},e={i:this.f.f,a:[],c:"as",C:"asu",g:0,j:0};if(!a)return e;this.f.s&&
(e.g=1);this.l=a;var f=a.length;if(f){b=this.C(b);var g=b.split(/\s+/),k=g.length,q,l=[],h;for(h=0;h<f;h++){var p=a[h],n=0,r=0;for(q=0;q<k;q++){var s=g[q],m=10*(p.o==s)+5*(p.a==s),v=0<=p.x.indexOf(" "+s);if(0<=p.t.indexOf(s)||0<=p.e.indexOf(s)||0<=p.u.indexOf(s)||v){var u=10*c(p.t,s),t=5*c(p.e,s),s=4*c(p.u,s);v&&10>m&&(m=10+p.z);u>m&&(m=u);t>m&&(m=t);s>m&&(m=s)}m&&(r++,n+=m)}0<n&&(q=r/k,l[l.length]={s:(3*p.p+n)*q*q,c:p})}l.sort(function(a,b){return b.s-a.s});f=l.length;5<f&&(20<f&&(f=20),h=gsv(),
c=po(this.f.f),c=h.h-c.y,h=h.H-10,c<h&&(h=c),h=Mf((h-45)/36),f>h&&(f=h),3>f&&(f=3));if(0<f){c=5<f?5:f;k=l[0].s;p=0.7*k;n=0.2*k;q=1;r=0;for(h=1;h<f;h++){g=k;k=l[h].s;if(k<n){f=h;break}m=g-k;h<c&&m>q&&g>p&&(q=m,r=h)}if(3<r||1.2>q)r=0;if(r){for(h=0;h<r;h++)d(e,l[h].c,1);e.a[e.a.length]={s:1}}l=l.slice(r,f);f=l.length;l.sort(function(a,b){return a.c.n.localeCompare(b.c.n)});for(h=0;h<f;h++)d(e,l[h].c,0)}else e.a[0]={n:"No matches",s:2,h:0,c:"ash"};this.f.s&&(e.a[e.a.length]={u:"/worldclock/",n:"World Clock",
s:100,h:1});return e}};
AC.prototype.U=function(){var a=this,b=function(b){b&&(0===b.a.length&&(b.a[0]={n:"Loading...",s:2,c:"ash"}),ifsm(a.f,b))},c=function(c){var d;a.c[c]={};var e="/scripts/completion.php?query="+encodeURIComponent(c);a.f.x&&(e+="&xd="+a.f.x);jcb(e,function(e){e=e.split("\n");var k=e.length,h=[],p;for(p=0;p<k;p++){var n;n=e[p].split("\t");7<n.length?n={i:n[0],p:n[1],o:n[2],a:n[3],n:n[4],t:a.C(n[4]),s:n[5],e:a.C(n[5]),c:n[6],u:a.C(n[6]),f:n[7],x:" "+n[8]+" ",z:n[9]-0}:("CONV"===n[0]&&(a.h[n[1]]=n[2]),
n=void 0);n&&h.push(n)}a.c[c].d=h;d=a.B(h,c);b(d)})},d=function(){var b;b=a.p;var d=a.c[b];d?b=d.d?a.B(d.d,b):a.B(a.l,b):(c(b),b=a.B(a.l,b));return b},e;2<=a.p.length&&(e=d(),b(e));e||pM.k()};AC.prototype.A=function(a,b){this.f=a;b=b.replace(/^\s+/g,"").replace(/\s+$/g,"").replace(/\s+/," ");this.p=b.toLowerCase();this.U()};function ifsm(a,b){a.m=b;a.u=-1;mena(a.n,b);mens(a.n,a.f)}
function ifd(a){var b=a.f,c=b.value,d=a.n.indexOf("txt");if(0<d){var e=b.form[a.n.slice(0,d)];if(e){var f=":";if(a.H&&a.T){var g=a.T.toLowerCase();0<=c.toLowerCase().indexOf(g)&&(f=a.H)}e.value=f}}if(a.e){e=a.t;f=11;b={i:b,a:[]};if(1==e.length){var g=d=c.replace(/\D/g,""),k,q=2,l=0;a.i=1;"y"==e&&(l=(new Date).getFullYear()-5,q=d.length,0<q&&(4>q&&(d+="1005".slice(q)),l=d.slice(0,4)-5),a.a=3999,q=4);"m"==e&&(l=1,f=12,a.a=12,k=" Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "));"M"==e&&(l=
1,f=36,a.a=36,b.r=12);"d"==e&&(l=1,f=31,a.a=31,b.r=10);l=lim(l,1,3989);"w"==e&&(l=0,f=54,a.a=53,b.r=15);if("i"==e||"s"==e)l=0,f=60,a.i=0,a.a=59,b.r=10;if("h"==e)for(l=0,f=24,a.i=0,a.a=23,b.r=12,k=[],d=0;d<f;d++)k[d]=(d+11)%12+1+(12>d?"am":"pm");for(d=0;d<f;d++){var h=k?" - "+k[l]:"";b.a[b.a.length]={n:pf(l,q),d:h,h:g==l};l++}ifsm(a,b)}2==e.length&&(a.l=1,a.o||"ci"==e&&getAC(e).A(a,c))}}function ifku(a,b){return ifd(a)}function ifpd(a){a.preventDefault&&a.preventDefault();a.returnValue=!1}
function ifkd(a,b){var c,d=a.f,e,f=!0;c=(e=window.event)?e.keyCode:b.which;var g=a.u,k=a.m,q=a.l&&k;e=0;27==c&&(a.e=0,pM.k());38==c&&(e=-1);40==c&&(e=1);if(e){if(q){f=k.a.length-1;for(c=0;3>c&&(-1==g?(a.o=d.value,g=0<e?0:f):g+=e,g>f&&(g=-1),-1!=g&&k.a[g].s);c++);d.value=0<=g?k.a[g].n:a.o;0>g&&(a.o=null);a.u=g;menh(g);return!1}g=d.value-0;0<=g&&(g+=e);a=fh[d.name];if(!a||!a.a||a.i<=g&&a.a>=g)d.value=g,f=!1}else if(13==c){if(0<=g&&q)return mech(k,k.a[g]),ifpd(b),!1}else a.o=null;ifd(a);return f}
function ifs(a){var b=a.u;return a.s&&0<=b?!1:!0}function ifcb(a,b,c){pM.z(50);gA(a,"tad-va")&&va(a.name,a)}function ifc(a,b,c,d){var e=a.name,f=fh[e];f||(f={n:e,f:a,t:b},fh[e]=f,b=e.indexOf("txt"),0<b&&(e=e.slice(0,b),e=a.form[e])&&(f.H=e.value,f.T=a.value),oael(a,"keydown",function(a){ifkd(f,a)},0),oael(a,"keyup",function(a){ifku(f,a)},0),oael(a,"blur",function(b){ifcb(a,f,b)},0),c&&(f.s=1,oael(a.form,"submit",function(){return ifs(f)})),d&&(f.x=d));f.e=1;return ifd(f)}
function ofs(a,b){var c=0,d,e,f=window,g="directories=no,location=no,menubar=no,resizable=yes,scrollbars=no,status=no,toolbar=no";if(e=f.screen)c=e.availHeight-30,d=e.availWidth-10;b?(g+=",left=0,screenX=0,top=0,screenY=0,fullscreen=yes",c&&(g+=",height="+c+",innerHeight="+c+",width="+d+",innerWidth="+d)):g+=",height=180,width=320";if(f.open(a.href,"_blank",g))return!1;alert("Could not open the popup-window, maybe there is a popup-blocker installed");b&&c&&(f.moveTo(0,0),f.resizeTo(d,c));return!0}
function jco(a,b,c,d){phg(b,b,function(b){pM.A('<table id=CB><thead><tr><td id=CT><a href="javascript:jcc()"><img class=fr src="//c.tadst.com/gfx/x3.png" alt=close width=18 height=18></a><div class=tc><strong>'+c+"</strong></div></td></tr><tr><td id=jcdiv>"+b+"</td></tr></table>",a,d)});return!1}function jcc(){pM.k()}function ges(a){return Mf(0.001*a)}
TO={co:{},e:0,f:0,j:0,J:0,p:0,s:0,t:"",z:1E3,Z:0,y:-1,C:[],gco:function(a){return TO.co[a]},dt:function(){return dt()+this.j},aC:function(a){a&&(this.C[this.C.length]=a)},S:function(a){a=a?"&r="+a:"";var b=dt(),c=this;jcb("/scripts/ts.php?ut="+b+"&cb="+Mr()+a,function(a){var e=dt(),e=(b+e)/2;c.j=Mf(1E3*parseFloat(a)-e);c.y=e-b+50;c.U();iH("ref","At time of loading, accuracy was within "+Math.round(c.y)/1E3+" seconds")})},Y:function(a){var b=this;40>b.s++&&(a+="_"+b.s,window.setTimeout(function(){b.S(a)},
2500))},R:function(a,b,c){var d="p"+b;if(a[d]!==c&&(a[d]=c,d=a[b])&&(ih(d,c),a=a.E))for(var e in a)d=a[e],this.R(d,b,c)},tO:function(a,b){var c=a.t,d=null,e;for(e=0;e<c.length;e++){var f=c[e];if(f.t>b)break;d=f;e&&(d.C=e)}return d?d:{a:"",o:0}},uL:function(a,b){var c=this.tO(cks[a],ges(b));return new Date(+b+1E3*c.o)},gF:function(a,b,c,d){var e=cks[a];a=this.tO(e,ges(b));b=new Date(+b+1E3*a.o);d=d?d(b):e.f(b);c&&a.a&&(d+=" "+a.a);return d},U:function(){var a,b,c,d=[],e=this,f=e.dt(),g=e.p;e.p=f;if(ges(f)>
et)rf("tz1","Will refresh in 10 seconds",10,0);else{if(g){g=f-g;if(e.f>f){rf("tz1","Clock has gone backward - will refresh soon",7,0);return}3E4<g&&(c="f");-25>g&&(c="b");if(c){e.Y(c+g);return}}else e.f=f;e.J&&(f+=e.J);c=e.Z?0.001*f:ges(f);if(c!=e.e)for(a in e.e=c,it(e.C,function(a){a(f)}),cks){var g=cks[a],k=e.tO(g,c);b=k.o;var q=k.a,k=k.d;if(""!==b&&g.c){var l=g.c,h=ges(l.t-f+999);l.z&&0>h&&(h=0);h!=l.p&&(l.f?ih(l.f1,l.f(h)):(0>h&&0<=l.p&&(ih(l.u1,"since"),ih(l.u2,"since")),l.p=h,0>h&&(h=-h),it(l.l,
function(a){var b=a.f,c=Mf(h/b.f);b.m&&(c%=b.m,l.P&&(c=pf(c,l.P)));e.R(a,"n1",c);e.R(a,"n2",a.u[1!=c?1:0])})))}if(""!==b){var p=new Date(1E3*(c+b));if(g.p){g.p(g,p,a,g);var n=g.E;if(n)for(var r in n)g.p(n[r],p,r,g)}g.d1&&(e.R(g,"d1",g.f(p)),g.u&&(b=(Mf((c+b)/86400)+4)%7,d[b]=(d[b]||0)+g.C,window.dsts&&(e.R(g,"d3",k?dsts:""),d[7]=(d[7]||0)+g.C*(k||0))));g.s&&g.s.f(g.s,p,g.g);g.S&&it(g.S,function(a){a.draw(+p)});e.R(g,"d2",q)}}if(window.updwds&&d.length&&(a=d.join(","),a!=e.t))for(e.t=a,b=0;8>b;b++)if(a=
d[b]||0,r=gf("smwd"+b))sd(r,a?1:0),iH("smwi"+b,updwds(a));f=e.dt();setTimeout(function(){e.U()},e.z-f%e.z)}},icks:function(a){function b(a,b,c){function d(a,b){var c=-(Mf(b)%16)*e+"px",f=-Mf(b/16)*e+"px";a.style.backgroundPosition=c+" "+f}var e=c.s;b=ges(+b);d(a.h,61+(b+450)%43200/900);d(a.m,1+b%3600/60);d(a.s,109+b%60)}function c(a,b,c){function d(a,b){m.beginPath();m.moveTo(a,0);m.lineTo(b,0);m.stroke()}function e(a,b,c,f,g){m.save();m.lineWidth=a;g&&(m.strokeStyle=g);m.rotate(b*v/30);d(-c*s,f*
s);m.restore()}var f=c.s;c=40<f;var g=100>f,s=f/2,m=a.c,v=Math.PI;m.save();m.clearRect(0,0,f,f);m.translate(s,s);m.rotate(-v/2);m.lineCap="butt";if(g)for(m.beginPath(),m.arc(0,0,s-2,0,2*v,!0),m.fillStyle="#fff",m.fill(),m.lineWidth=c?4:1,m.strokeStyle=c?"#353535":"#065947",m.stroke(),f=c?0.76:0.7,a=0;60>a;a+=5)m.lineWidth=c?a%15?2:4:1,d(0.985*(s-1),s*f),m.rotate(v/6);m.lineCap="round";f=ges(+b);b=f%60;a=f/60%60;f/=720;c?(e(2,f,0.14,0.46,"#000"),e(1.5,a,0.14,0.76,"#000"),e(1,b,0.28,0.76,"#e00f21")):
(e(1,f,0,0.5,"#065947"),e(1,a,0,0.9,"#065947"));m.restore()}function d(a){var d=cE("canvas"),e=a.s=a.s||56;if(d&&d.getContext)return a.s=e,sA(d,"width",e),sA(d,"height",e),a.c&&(d.className=a.c),ac(d,"clk"),{f:c,e:d,c:d.getContext("2d")};var f=function(a){var b=cE("div"),c=b.style;c.background="url(//c.tadst.com/gfx/canvas/nclk"+e+".png?1)";es(b,{w:e,h:e});a&&(c.position="relative",aCh(a,b));return b},d=f(),g=f(d),n=f(g),f=f(n);a.c&&(d.className=a.c);ac(d,"clkimg");return{f:b,e:d,s:f,m:g,h:n}}var e,
f=[{n:"s2",f:1},{n:"m2",f:60},{n:"h2",f:3600},{n:"d2",f:86400},{n:"w2",f:604800},{n:"s1",f:1,m:60},{n:"m1",f:60,m:60},{n:"h1",f:3600,m:24},{n:"d1",f:86400},{n:"dw1",f:86400,m:7},{n:"w1",f:604800}],g=function(a,b){TO.co[a]=b;b.d1=gf(a);b.d2=gf(a+"a");b.d3=gf(a+"s");if(b.g)if(2==b.g.t){var c=function(c){if(c=gf(a+c))b.S||(b.S=[]),b.S.push(new Clck(c,a))};c("clk");c("mapclk")}else if(c=d(b.g))b.s=c,b.d1.parentNode.insertBefore(c.e,b.d1);b.u="p"==a.charAt(0);var g=b.c;if(g){var p={s:["second","seconds"],
m:["minute","minutes"],h:["hour","hours"],d:["day","days"],w:["week","weeks"]};(c=g.u)&&(p=1===c?{s:["sec","secs"],m:["min","min"],h:["hrs","hrs"],d:["day","days"],w:["wk","wks"]}:c);g.f1=gf(a+"_f1");g.u1=gf(a+"_u1");g.u2=gf(a+"_u2");g.l=[];it(f,function(b,c){b=f[c];var d=a+"_"+b.n;g.l[c]={f:b,n1:gf(d),n2:gf(d+"t"),u:p[b.n.charAt(0)]}})}b.C=1;b.e&&(c=b.e.split(","),b.E={},it(c,function(a){a=a.replace(/^(\d)/,"p$1");b.E[a]={};b.C++}),e(b.E))};e=function(a){for(var b in a)g(b,a[b])};e(a)},init:function(){var a=
window.cks;"object"==typeof a&&(this.icks(a),window.TO_noupd||this.S())}};
(function(){function a(a,d){this.d=TO.dt();this.N=gf(a);b[d]=this;var e=document.createDocumentFragment();this.h=cE("div",{"class":"hour"},e);this.m=cE("div",{"class":"min"},e);this.s=cE("div",{"class":"sec"},e);this.o=cE("div",{"class":"dot"},e);this.t=cE("div",{"class":"time clk-tm"},e);this.T=cE("span",null,this.t);this.D=cE("span",{"class":"block small"},this.t);this.F=e;this.W=this.N.offsetWidth;this.H=this.N.offsetHeight;this.debug=!1;this.night=!!gA(this.N,"data-Clck-night");this.showSeconds=
"false"!==gA(this.N,"data-Clck-showSeconds")}var b={};a.update=function(a,d,e,f){if(a=b[e])e=0,f=f.X,e=EVC&&EVC.fix&&f?1E3*f.local:+d,a.draw(e)};a.prototype={A:function(a,b,e,f){!1===f||0===this.d?sd(a,0):(angle=this.d/b%e*(360/e),b=a.style,UA.trans?b[UA.trans]="rotate("+angle+"deg) "+(UA.d3?"translateZ(0)":""):(b.marginTop="",b.marginLeft="",b.filter=UA.mat(angle),b.marginTop=(this.H-a.offsetHeight)/2+"px",b.marginLeft=(this.W-a.offsetWidth)/2+"px"))},S:function(){this.A(this.h,36E5,12);this.A(this.m,
6E4,60);this.A(this.s,1E3,60,this.showSeconds)},draw:function(a){this.d=a;this.night=!1;ac(this.N,"night",this.night);this.S();this.F&&(aCh(this.N,this.F),delete this.F)}};window.Clck=a})();elh={};elc={};fh={};window.TD||(TD={});function ael(a,b,c,d){if(a){if("string"==typeof a&&(a=gf(a),!a))return;a.addEventListener?a.addEventListener(b,c,d):a.attachEvent&&a.attachEvent("on"+b,c)}}function aelw(a,b,c){ael(window,a,b,c)}
function oael(a,b,c,d){var e=a.id;e||(e=a.name);e||(e=a.href);e=b+":"+e;elh[e]||(elh[e]=1,ael(a,b,c,d))}function aelc(a,b){var c=gf(a);ael(c,"click",function(a){a=ev(a);ifpd(a.e);b(c,a);return!1},!0)}blo=-1;function bls(a){var b=gf("FBD");sd(b,blo);0>blo&&(a=a.href,a=a.match(/\.html/)?a.replace(".h","-frame.h"):a.match(/\?/)?a.replace("?","-frame?"):a+"-frame",ih(b,'<iframe id=FBF src="'+a+'" width=980 height=500 frameborder=0>webmaster@timeanddate.com</iframe>'));blo=!blo;return!1}
function blc(){blo=0;bls();blo=-1}function ev(a){var b={};a?b.k=a.which:(a=window.event,b.k=a.keyCode);if(b.e=a)b.s=a.target||a.srcElement;return b}
function bli(){var a=wl();if(a){var b="?url="+a.pathname;(a=a.search)&&(b+=encodeURIComponent(a));a=function(a,b,e,f){a&&document.write('<a href="'+a+'"  alt="'+e+'"'+f+">"+b+"</a> | ")};a("/information/feedback.html"+b,"Feedback","Send feedback to us",' onclick="return bls(this)"');8<b.length?a("/createshort.html"+b,"Short URL","Create a short URL to this page",""):a("/information/linkpolicy.html","Link policy","About linking","")}}
function ott(a,b,c){oael(a,"mouseout",function(a){pM.z()});c=b;ttt&&ttt[b]&&(c=ttt[b]);c='<div id=ttb onmouseover="pM.y()" onmouseout="pM.z()">'+c+"</div>";b=ap(a);c=pM.h(c);jp(b,c,a,-1,0);ep(c,b)}function calp(a,b){0<=a.className.indexOf("disabled")||phg("calp","/scripts/field/calpop",function(c){pM.A(c,a,null,!0);CPop.init(pM,b,document.f)})}
function vad(a,b,c){var d=0,e=[],f=function(a,b,c){if(a){var f=gfv(a),h=f.replace(/[\s\.\-\,]/g,"");h!=f&&(a.value=h);""!==h&&null!==h&&(h-=0,h>=b&&h<=c&&(e.push(h),d++))}};f(a,1,3999);f(b,1,12);f(c,1,31);if(3==d){a=e[0];b=e[1];c=e[2];if(1925<a){f=31;if(4==b||6==b||9==b||11==b)f=30;2==b&&(f=28+(0==a%4)-(0==a%100)+(0==a%400));if(c>f)return null}f=new Date(0);f.setUTCFullYear(a);f.setUTCMonth(b-1);f.setUTCDate(c);return f}return null}
function vat(a,b,c){function d(){ac(c,"error",0)}function e(){d();ac(c,"error",1)}function f(a,b){if(l<a||l>b)return e(),1;d()}var g=b.match(/(\w)(\d+)/),k,q=c.value,l=q.replace(/[\s\.\-\,]/g,"");if(l){l!=q&&(c.value=l);var h;if("date"==a&&(g?(h=g[1],k=g[2],k=["y"+k,"m"+k,"d"+k]):("year"==b&&(h="y"),"month"==b&&(h="m"),"day"==b&&(h="d"),h&&(k=["year","month","day"])),k)){if("y"==h&&f(1,3999)||"m"==h&&f(1,12)||"d"==h&&f(1,31))return;var p=[],n=[];it(k,function(a){if(a=gf(a)){var b=a.value;null!==b&&
""!==b&&(p.push(b-0),n.push(a))}});if(3==p.length){c=n[2];var q=p[0],r=p[1],s=p[2];if(1925<q){var m=31;if(4==r||6==r||9==r||11==r)m=30;2==r&&(m=28+(0==q%4)-(0==q%100)+(0==q%400));if(s>m){e();return}}}d()}"time"==a&&(g?(h=g[1],k=g[2],k=["h"+k,"i"+k,"s"+k]):("hour"==b&&(h="h"),"min"==b&&(h="i"),"sec"==b&&(h="s"),h&&(k=["hour","min","sec"])),k&&("h"==h&&f(0,23),"i"==h&&f(0,59),"s"==h&&f(0,59)))}else d()}function va(a,b){if(a){if(b){var c=gA(b,"tad-va");c&&vat(c,a,b)}(c=elc[a])&&c()}}
function elca(a,b){elc[a]=b}function abrd(a,b){return'<a href="javascript:modph()" class="close" title="Close"><img alt="close" src="//c.tadst.com/gfx/n/popup-close.png"/></a><h1 class=title>'+a+"</h1>"+b}
function modps(a,b,c){a=ghj(a);c="<div class=modal><div class=modal-dialog><div class=modal-content><div class=modal-header><button class=close onclick=modph()>\u00d7</button><h2 class=modal-title>"+(c||"Info")+"</h2></div>"+a.h+"</div></div></div>";var d=gf("mpo");ih(d,c);eval(a.j);oael(d,"click",function(a){a=ev(a).s;a!=d&&a.parentNode!=d||modph()});oael(window,"keydown",function(a){27==ev(a).k&&modph()});sd(d,2)}function modpop(a,b,c){a&&jcb(a,function(a){modps(a,b,c)});return!1}
function modph(a){he("mpo",0);"function"===typeof a&&a()}function popad(a,b,c){var d=wl();c+="?ref="+escape(d.pathname+d.search);aelc(a,function(){modpop(c,1,b)})}function popadlogin(a){popad(a,"Login","/custom/loginframe.html")}function popadreg(a){popad(a,"Register a new account","/custom/createframe.html")}function hsl(a,b){if(a){a.style.overflow="hidden";var c=gcs(a,"height"),d=1,e=function(){c-=d;d++;0<c?(es(a,{h:c}),window.setTimeout(e,20)):sd(a,0)};window.setTimeout(e,b)}}
switching=function(){function a(a){c=a;it(b,function(a){var b=a==c;ac(gf("ec"+a),"active",b);sd(gf(a),b)})}var b=arguments,c=b[0];it(b,function(b){aelc("ec"+b,function(){a(b)})});a(c)};function extfield(a,b,c){TD.C=function(b,c){var f=document.f[a],g=f.options;if(g){var k=g.length;g[k]=new Option(c,b);f.selectedIndex=k}else if(f.value=b,g=document.f[a+"txt"])g.value=c;va(a,f)};modpop("/scripts/field/"+b,1,"Select city")}function extlocs(a,b){b&&(TD.sh=1);extfield(a,"location","Select city")}
function exttzs(a,b){b&&(TD.sh=1);extfield(a,"timezone","Select time zone")}function pn(){return window.performance&&window.performance.now?window.performance.now():+new Date}var raf=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a){window.setTimeout(function(){a(pn())},1E3/60)}}();
function lo(){document.cookie="TIMEANDDATE_LOGIN=;domain=.timeanddate.com;path=/;expires="+(new Date(0)).toGMTString();wl().reload();return!1}
function main(){var a=window;if(!a.hasRun){a.hasRun=1;popadlogin("poplogin");popadreg("popreg");popad("popin","You are logged in","/custom/loggedinframe.html");aelc("popout",lo);var b=function(){modpop("/scripts/tzq.php?type=homecity",1,"Set Home Location")};aelc("popchi",b);aelc("chi",b);ia(TD.mena,function(b,c){c.f&&(c.f=a[c.f]);mena(b,c)});var b=function(a){aelc(gf("ftbx"+a),function(){var b;for(b=0;4>b;b++){var c=gf("ftbx"+b);c&&(he("feat"+b,b==a),c.className=b===a?"active":"")}})},c;for(c=0;4>
c;c++)b(c);scrlr=function(){function b(a,c){f.push({e:a,c:c})}function c(b){var d=(a.pageYOffset||ddE().scrollTop)>g;it(f,function(a){ac(a.e,a.c,d)})}var f=[],g;return{init:function(f){b(f,"sticky");g=f.offsetTop;ael(a,"scroll",c);c()},addEle:b,to:c}}();(b=gf("nav"))&&scrlr.init(b);TO.init()}}
(function(){function a(a){sd(a,1);ael(a,"mouseover",function(){var g=c[gA(a,"data-social")];g&&(b(g.src,g.id),clearTimeout(f),it(d,function(b){a!==b&&ac(b,"hover",0)}),ac(a,"hover",1),e=a)});ael(a,"mouseout",function(){f=setTimeout(function(){g||ac(a,"hover",0)},2E3)});d.push(a)}function b(a,b){var c,d=gebtn("script")[0];gf(b)||(c=cE("script",{id:b,src:a}),d.parentNode.insertBefore(c,d))}var c={facebook:{src:"//connect.facebook.net/en_GB/all.js#xfbml=1&appId=119413198130333",id:"facebook-jssdk"},
twitter:{src:"//platform.twitter.com/widgets.js",id:"twitter-wjs"},google:{src:"//apis.google.com/js/plusone.js",id:"google-js"}},d=[],e,f,g=!1;window.gpluso=function(){g=!0;clearTimeout(f)};window.gplusc=function(){g=!1;ac(e,"hover",0)};it(gebc("social"),function(b){a(b)});window.mtt&&!navigator.appVersion.match(/MSIE [3-7]/)&&it(gebc("mtt"),function(a){ael(a,"mouseover",function(b){if(b=gA(a,"title")){if("IMG"===a.tagName||"INPUT"===a.tagName){var c=dce("div",{"class":a.className});a.className=
"";a.parentNode.insertBefore(c,a);aCh(c,a);c.blur();c.focus()}else c=a;sA(c,"data-mtt",b);sA(a,"title","")}})})})();(function(){function a(a){ac(a,"bloat-enabled",!hC(a,"bloat-enabled"))}aelw("load",function(){var b=[];b.push(gf("bloat"));for(var c=1,d;d=gf("bloat"+c);)b.push(d),c++;it(b,function(b){aelc(b,a);b=gebtn("figcaption",b);(2<=b.length&&""===b[1].innerHTML||1===b.length)&&sd(b[0],2)})})})();aelw("load",main);
(function(){function a(){var b=window.UPD,c=0<TO.y?1E4:1E3;if(b){var d=TO.dt(),e,f=function(a){if(!a.d){var b=e-d;if(0>b){var b=a.typ,f=a.val;"reload"==b&&location.reload();"html"==b&&iH(a.id,f);if("attr"==b){var l=gf(a.id);l&&sA(l,a.nam,a.val)}"img"==b&&(l=gf(a.id))&&(l.src=f);"imgf"==b&&((new Image).src=f);if("js"==b)try{eval(f)}catch(h){window.exception=h}a.d=1}else b<c&&(c=b)}};it(b,function(a){e=a.tim;it(a.lst,f)})}setTimeout(a,c)}a()})();
(function(){var a=function(a,c){var d=this;d.e=gf(a);d.e.stickytable=d;d.o=eval("("+gA(d.e,"data-options")+")")||c||{};d.p=d.o.offsettop||40;d.b=d.o.offsetbottom||0;d.w=cE("div",{"class":"sticky-wr"});d.T();d.d=gebtn("thead",d.e)[0];d.l=gebtn("tbody",d.e)[0];d.f=gebtn("tfoot",d.e)[0];d.S();aelw("scroll",function(a){d.C(a)});aelw("resize",function(a){d.Z(a)})};a.prototype.T=function(){this.e.parentNode.insertBefore(this.w,this.e);aCh(this.w,this.e)};a.prototype.S=function(){ac(this.e,"sticky-en",0);
this.W(this.d,!0);this.W(this.l);this.d.style.width=this.l.offsetWidth+"px";this.f&&this.W(this.f);this.y=ap(this.e).y;this.h=this.e.offsetHeight;ac(this.e,"sticky-en",1);this.a=this.d.offsetHeight;this.l.style.borderTop=this.a+"px solid transparent"};a.prototype.W=function(a,c){var d=arrclone(a.children),e,f=c?d.length:1;for(e=0;e<f;e++){var g=arrclone(d[e].children),k=[];it(g,function(a){k.push(a.offsetWidth)});it(g,function(a,b){a.style.width=k[b]+"px"})}};a.prototype.P=function(){var a=this,c=
(document.body.scrollTop||ddE().scrollTop)-a.y,d=a.p;a.d.style.top=(c>=-d&&c<a.h-a.b-a.a-d?c+d:c>=a.h-a.b-a.a-d?a.h-a.b-a.a:1)+"px";a.s||(a.s=setTimeout(function(){a.y=ap(a.e).y;a.s=null},300))};a.prototype.C=function(a){this.P()};a.prototype.Z=function(a){var c=this;c.t&&clearTimeout(c.t);c.t=setTimeout(function(){c.S();c.P()},300)};window.Sticky=a})();
(function(){function a(c,d){c&&c.preventDefault&&c.preventDefault();ac(f,"searchVisible","searchMenu"===d?!hC(f,"searchVisible"):0);ac(f,"navVisible","navMenu"===d?!hC(f,"navVisible"):0);ac(f,"socialVisible","socialMenu"===d?!hC(f,"socialVisible"):0);hC(f,"searchVisible")||hC(f,"navVisible")||hC(f,"socialVisible")?(e.onkeyup=b,setTimeout(function(){e.onclick=function(b){b=b||event;b=b.target||b.srcElement;for(var c=!0;b.parentNode;)b.id===d&&(c=!1),b=b.parentNode;c&&a()}},100)):(e.onkeyup=null,e.onclick=
null);return!1}function b(b){27===(b||event).keyCode&&a()}function c(a,b,c){a.preventDefault();ac(b.parentNode,"selected",c);ac(b.parentNode.parentNode,"hasSelected",c);return!1}function d(a){return!hC(f,"navVisible")||hC(this.parentNode,"selected")?!0:c(a,this,!0)}var e=document,f=e.body;(function(){var b=[],f=[];try{b=e.querySelectorAll?e.querySelectorAll("#nav > ul > li > a:not(.nav-back)"):[],f=e.querySelectorAll?e.querySelectorAll("#nav > ul > li > a.nav-back"):[]}catch(q){}ael("navButton","click",
function(b){a(b,"navMenu")});ael("searchButton","click",function(b){a(b,"searchMenu")});ael("closeSearch","click",function(b){a(b,"searchMenu")});ael("socialButton","click",function(b){a(b,"socialMenu")});ael("closeSocial","click",function(b){a(b,"socialMenu")});it(b,function(a){ael(a,"click",d,!1)});it(f,function(a){ael(a,"click",function(a){c(a,this,!1)},!1)})})()})();
